import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          {/* use Link instead of a tag */}
          <Link href="/">Home</Link>
          <Link href="/list">List</Link>
          <Link href="/register">Register</Link>
        </div>
        {/* page.js goes into this line 
          page.js 옆에 layout.js가 있으면 그걸로 감싸서 보여주고, 그 상위 폴더에 layout.js 가 있으면 그걸로 한번 더 감싸주고, 모든 상위 폴더 반복
        */}
        {children}
      </body>
    </html>
  )
}
